services:
  # === API FastAPI ===
  - type: web
    name: techgear-api
    runtime: python
    buildCommand: cd techgear_api && pip install -r requirements.txt
    startCommand: cd techgear_api && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
    healthCheckPath: /

  # === Portal Django ===
  - type: web
    name: techgear-web
    runtime: python
    buildCommand: cd techgear_web && pip install -r requirements.txt
    startCommand: cd techgear_web && python manage.py collectstatic --noinput && cd .. && cd techgear_web && gunicorn techgear_web.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: TECHGEAR_API_BASE_URL
        sync: false
      - key: TECHGEAR_API_TIMEOUT
        value: "10"
      - key: PYTHON_VERSION
        value: "3.11"
    healthCheckPath: /
